import Head from 'next/head'
// import Image from 'next/image'
import Link from 'next/link';
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>SOUNDBOARDS+</title>
        <meta name="description" content="Generated by Dat Mothafucka P" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2 className={styles.title}>
          Welcome 2 <a href="https://main.d27b4f0rprnivy.amplifyapp.com/">TONEDEF</a>
        </h2>

        <div className={styles.grid}>

        <div className={styles.card} >
            <h1 className="title">
            Play{' '}
            <Link href="/soundboards/firstsoundboard">
              <a>SOME KORDS &rarr; </a>
            </Link>
          </h1>
        </div>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            {/* <img src="/vercel.svg" alt="Vercel Logo" width={72} height={16} /> */}
          </span>
        </a>
      </footer>
    </div>
  )
}
