import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>SOUNDBOARDS+</title>
        <meta name="description" content="Generated by Dat Mothafucka P" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <h2 className={styles.title}>
          Welcome 2 <a href="https://main.d27b4f0rprnivy.amplifyapp.com/">TONEDEF</a>
        </h2>

        <div className={styles.grid}>

        <div className={styles.card} >
            <h1 className="title">
            <Link href="/soundboards/soundboardmobile">
              <a>(MOBILE) PLAY SOME KORDS &rarr; </a>
            </Link>
          </h1>
        </div>


        <div className={styles.card} >
            <h1 className="title">
            <Link href="/soundboards/soundboarddesktop">
              <a>(DeSKTOP) PLAY SOME KORDS &rarr; </a>
            </Link>
          </h1>
        </div>

        </div>
      </main>

      <footer className={styles.footer}>
      </footer>

    </div>
  )
}
