import Head from 'next/head'
// import Image from 'next/image'
import Link from 'next/link';
import styles from '../styles/Home.module.css'
import { createTheme, ThemeProvider, styled } from '@mui/material/styles';
export default function Home() {

  const theme = createTheme({
    typography: {
      fontFamily: [
        'Syne Mono',
        '-apple-system',
        'BlinkMacSystemFont',
        '"Segoe UI"',
        'Roboto',
        '"Helvetica Neue"',
        'Arial',
        'sans-serif',
        '"Apple Color Emoji"',
        '"Segoe UI Emoji"',
        '"Segoe UI Symbol"',
      ].join(','),
    },
  });


  return (
    <ThemeProvider theme={theme}>

    <div className={styles.container}>
      <Head>
        <title>SOUNDBOARDS+</title>
        <meta name="description" content="Generated by Dat Mothafucka P" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Syne+Mono&display=swap" rel="stylesheet" />
      </Head>
      <main className={styles.main}>
        <h2 className={styles.title}>
          Welcome 2 <a href="https://main.d27b4f0rprnivy.amplifyapp.com/">TONEDEF</a>
        </h2>

        <div className={styles.grid}>

        <div className={styles.card} >
            <h1 className="title">
            Play{' '}
            <Link href="/soundboards/firstsoundboard">
              <a>SOME KORDS &rarr; </a>
            </Link>
          </h1>
        </div>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            {/* <img src="/vercel.svg" alt="Vercel Logo" width={72} height={16} /> */}
          </span>
        </a>
      </footer>

    </div>
</ThemeProvider>
  )
}
